### ISSUE TITLE
KeyError 'fileType'

### ISSUE THREAD

**Issue by mcstoufer** [kstenerud/iOS-Universal-Framework#150]
I'm getting the following error as soon as the Mk8 script runs:
This is under XCode 5 and I am building an embedded framework.

```
PhaseScriptExecution Build\ Embedded\ Framework /Users/xxx/Library/Developer/Xcode/DerivedData/ECXWorkspace-bwmsvgsibaglvlfcuafjjugwkrgk/Build/Intermediates/ECXProject.build/Release-iphoneos/ECXProject.build/Script-C782073E14CF4F40003118D8.sh
    cd /Users/xxx/Projects/xxx/iOS/ECX2/ECXProject
    /bin/sh -c /Users/xxx/Library/Developer/Xcode/DerivedData/ECXWorkspace-bwmsvgsibaglvlfcuafjjugwkrgk/Build/Intermediates/ECXProject.build/Release-iphoneos/ECXProject.build/Script-C782073E14CF4F40003118D8.sh

UFW (M iphoneos): ERROR: Build failed
Traceback (most recent call last):
  File "/Users/xxx/Library/Developer/Xcode/DerivedData/ECXWorkspace-bwmsvgsibaglvlfcuafjjugwkrgk/Build/Intermediates/ECXProject.build/Release-iphoneos/ECXProject.build/Script-C782073E14CF4F40003118D8.sh", line 804, in <module>
    run_build()
  File "/Users/xxx/Library/Developer/Xcode/DerivedData/ECXWorkspace-bwmsvgsibaglvlfcuafjjugwkrgk/Build/Intermediates/ECXProject.build/Release-iphoneos/ECXProject.build/Script-C782073E14CF4F40003118D8.sh", line 737, in run_build
    project = Project(os.path.join(os.environ['PROJECT_FILE_PATH'], "project.pbxproj"))
  File "/Users/xxx/Library/Developer/Xcode/DerivedData/ECXWorkspace-bwmsvgsibaglvlfcuafjjugwkrgk/Build/Intermediates/ECXProject.build/Release-iphoneos/ECXProject.build/Script-C782073E14CF4F40003118D8.sh", line 200, in __init__
    self.compilable_sources = self.get_build_phase_files('PBXSourcesBuildPhase', lambda x: x['fileRef']['fileType'] in sourcecode_types)
  File "/Users/xxx/Library/Developer/Xcode/DerivedData/ECXWorkspace-bwmsvgsibaglvlfcuafjjugwkrgk/Build/Intermediates/ECXProject.build/Release-iphoneos/ECXProject.build/Script-C782073E14CF4F40003118D8.sh", line 300, in get_build_phase_files
    build_files = filter(filter_func, build_phase['files'])
  File "/Users/xxx/Library/Developer/Xcode/DerivedData/ECXWorkspace-bwmsvgsibaglvlfcuafjjugwkrgk/Build/Intermediates/ECXProject.build/Release-iphoneos/ECXProject.build/Script-C782073E14CF4F40003118D8.sh", line 200, in <lambda>
    self.compilable_sources = self.get_build_phase_files('PBXSourcesBuildPhase', lambda x: x['fileRef']['fileType'] in sourcecode_types)
KeyError: 'fileType'
Command /bin/sh failed with exit code 1
```

**Comment by Providnuk** [comment]
hamdan, I tried it, but got:

line 300
    build_phase = filter(lambda x: x['isa'] == build_phase_name, self.target['buildPhases'])[0]
              ^
IndentationError: expected an indented block
Command /bin/sh failed with exit code 1
