### ISSUE TITLE
Hello, found that there is a mistake, lead to can't compile

### ISSUE THREAD

**Issue by alwayslove** [kstenerud/iOS-Universal-Framework#211]
UFW (M iphonesimulator): ERROR: Build failed
Traceback (most recent call last):
File "/Users/admin/Library/Developer/Xcode/DerivedData/MtProtoKit-gzkxssspyozwjjbgmyuwkbgwnpjo/Build/Intermediates/MtProtoKit.build/Debug-iphonesimulator/MtProtoKit iOS.build/Script-D05A831218AFB3F9007F1076.sh", line 812, in 
run_build()
File "/Users/admin/Library/Developer/Xcode/DerivedData/MtProtoKit-gzkxssspyozwjjbgmyuwkbgwnpjo/Build/Intermediates/MtProtoKit.build/Debug-iphonesimulator/MtProtoKit iOS.build/Script-D05A831218AFB3F9007F1076.sh", line 787, in run_build
add_symlinks_to_framework(project)
File "/Users/admin/Library/Developer/Xcode/DerivedData/MtProtoKit-gzkxssspyozwjjbgmyuwkbgwnpjo/Build/Intermediates/MtProtoKit.build/Debug-iphonesimulator/MtProtoKit iOS.build/Script-D05A831218AFB3F9007F1076.sh", line 675, in add_symlinks_to_framework
attempt_symlink(os.path.join(base_dir, "Versions", "Current"), os.environ['FRAMEWORK_VERSION'])
File "/Users/admin/Library/Developer/Xcode/DerivedData/MtProtoKit-gzkxssspyozwjjbgmyuwkbgwnpjo/Build/Intermediates/MtProtoKit.build/Debug-iphonesimulator/MtProtoKit iOS.build/Script-D05A831218AFB3F9007F1076.sh", line 493, in attempt_symlink
os.stat(os.path.abspath(os.path.join(link_path, "..", link_to)))
OSError: [Errno 2] No such file or directory: '/Users/admin/Library/Developer/Xcode/DerivedData/MtProtoKit-gzkxssspyozwjjbgmyuwkbgwnpjo/Build/Products/Debug-iphonesimulator/MtProtoKit iOS.framework/Versions/A'
Showing first 200 notices only
Command /bin/sh failed with exit code 1

OSError: [Errno 2] No such file or directory: '/Users/admin/Library/Developer/Xcode/DerivedData/MtProtoKit-gzkxssspyozwjjbgmyuwkbgwnpjo/Build/Products/Debug-iphonesimulator/MtProtoKit iOS.framework/Versions/A'

Why did the folder does not exist?
Used in what place?

Please help me，Thank you!

**Comment by look1n** [comment]
You can find possible solution in https://github.com/kstenerud/iOS-Universal-Framework/issues/214
